### ISSUE TITLE
Add support for GFM-style checkbox task list

### ISSUE THREAD

**Issue by adam-p** [adam-p/markdown-here#259]
This is from a [Google Group post](https://groups.google.com/forum/#!topic/markdown-here/c5vnTBQcGaU).

Github supports an extension to Markdown for creating [checkbox task lists](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments). This MD:
```
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```

Turns into this:
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

In case this isn't obvious: An important aspect of the Github feature that won't (and can't) be supported is the the updating of the email (etc.) if the checkboxes are clicked. This makes sense for GH issues, not for email.

**Comment by adam-p** [comment]
This was also requested in #242, and the user wants to use it in Evernote. Unlike email, maybe Evernote will save the checkbox state? (I was thinking that they would be disabled, but maybe not...)

**Comment by chabad360** [comment]
Would be so appropriated.

**Comment by chabad360** [comment]
Would be sooooo appreciated! :+1:

**Comment by gkoberger** [comment]
There's code for this in #587.

**Comment by stephen147** [comment]
+1 for this.

Here's some info from here and looks fairly straight forward to implement.

http://blog.winddweb.com/implement-github-like-checkbox

**Comment by stephen147** [comment]
You can paste this into the raw text:

```
<input type="checkbox" class="task-list-item-checkbox" disabled checked>Test line 1
<input type="checkbox" class="task-list-item-checkbox" disabled>Test line 2
```

It displays like so when converted:

![image](https://user-images.githubusercontent.com/14054664/77012307-a5a6b200-6965-11ea-8a1b-dd0553a1f119.png)

Now, to find a way to change:
`- []` to `<input type="checkbox" class="task-list-item-checkbox" disabled checked>`

and

`- [x]` to `<input type="checkbox" class="task-list-item-checkbox" disabled>`

This does seem to be possible by wrapping html in the css code as per this:
https://www.quora.com/How-do-I-write-CSS-within-HTML
https://www.w3schools.com/html/html_css.asp

Same link to where the checkbox code is:
http://blog.winddweb.com/implement-github-like-checkbox
